# Generated by Django 5.0 on 2024-01-09 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbkform',
            name='Phone_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter a valid mobile number.')]),
        ),
    ]
