# Generated by Django 5.0 on 2024-01-22 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0002_alter_kbkform_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbkform',
            name='Name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='kbkform',
            name='Phone_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Enter a valid mobile number.', regex='^\\+\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='kbkform',
            name='Url',
            field=models.TextField(unique=True),
        ),
    ]
