# Generated by Django 5.0 on 2024-02-12 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0008_alter_kbkform_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter a valid mobile number.')])),
                ('Url', models.CharField(max_length=255, unique=True)),
                ('Company', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
