# Generated by Django 5.0 on 2024-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0010_rename_signin_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='#12345678', max_length=20),
        ),
    ]
