# Generated by Django 5.0 on 2024-01-22 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0003_alter_kbkform_name_alter_kbkform_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbkform',
            name='Phone_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter a valid mobile number.')]),
        ),
    ]
