# Generated by Django 5.0 on 2024-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0004_alter_kbkform_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbkform',
            name='Url',
            field=models.CharField(unique=True),
        ),
    ]
