# Generated by Django 5.0 on 2024-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0009_signup_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='image',
            field=models.ImageField(null=True, upload_to='media/userimage/'),
        ),
    ]
