# Generated by Django 5.0 on 2024-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0010_alter_signup_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='image',
            field=models.ImageField(null=True, upload_to='userimage/'),
        ),
    ]
