# Generated by Django 5.0 on 2024-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0011_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
