# Generated by Django 5.0 on 2024-02-16 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0013_signup_model_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_model',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup_model',
            name='otp',
        ),
        migrations.AddField(
            model_name='signup_model',
            name='auth_tocken',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
