# Generated by Django 5.0 on 2024-03-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0015_alter_signup_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='feedback',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='image',
            field=models.ImageField(null=True, upload_to='static/userimage/'),
        ),
    ]
