# Generated by Django 5.0 on 2024-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0016_signup_model_feedback_signup_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='feedback',
            field=models.TextField(default='', max_length=500),
        ),
    ]
