# Generated by Django 5.0 on 2024-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0019_remove_signup_model_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='feedback',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
