# Generated by Django 5.0 on 2024-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBKform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_no', models.IntegerField()),
                ('Url', models.TextField()),
                ('Company', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
