# Generated by Django 5.0 on 2024-02-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0009_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signin',
            new_name='signup',
        ),
    ]
