# Generated by Django 5.0 on 2024-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BKB_Home', '0012_signup_model_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
